main_prompt_path: prompts/interviewer_prompt.txt
main2_prompt_path: prompts/interview_assistant_prompt.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
report_prompt_path: prompts/report_prompt.txt
